version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    ports:
        - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio456
    command: server /data
