on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.0

  test:
    runs-on: ubuntu-latest

    services:
      minio:
        image: minio/minio:RELEASE.2021-06-17T00-10-46Z
        ports:
        - 9000:9000/tcp

    steps:
    - uses: actions/checkout@v2
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.1.0
    - uses: yokawasa/action-setup-kube-tools@v0.7.1
      with:
        kubectl: '1.21.2'
        tilt: '0.20.8'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - run: kubectl version
    - run: tilt version
    - run: env
      env:
        MINIO_HOST: localhost
        MINIO_PORT: ${{ job.services.minio.ports[9000] }}
