on:
  - push
  - pull_request

env:
  GOLANGCI_VERSION: v1.41.0
  GOLANG_VERSION: 1.16.5

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup minio
        run: |
          docker-compose up -d
          until curl http://127.0.0.1:9000; do sleep 1; done
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - run: go test ./...
