on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.0

  test:
    runs-on: ubuntu-latest

    container:
      image: golang:1.16.5-alpine

    services:
      minio:
        image: minio/minio:RELEASE.2021-06-17T00-10-46Z
        ports:
        - 9000:9000

    steps:
    - uses: actions/checkout@v2
    - run: go version
    - run: apk --update add curl
    - run: curl http://${MINIO_HOST}:${MINIO_PORT}
      env:
        MINIO_HOST: minio
        MINIO_PORT: ${{ job.services.minio.ports[9000] }}
