on:
  - push
  - pull_request

env:
  GOLANGCI_VERSION: v1.41.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=minio123" \
                     -e "MINIO_SECRET_KEY=minio456" \
                     minio/minio server /data
          export AWS_ACCESS_KEY_ID=minio123
          export AWS_SECRET_ACCESS_KEY=minio456
          export AWS_EC2_METADATA_DISABLED=true
          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://testbucket
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - run: go version
      - run: curl http://${MINIO_HOST}:${MINIO_PORT}
        env:
          MINIO_HOST: localhost
          MINIO_PORT: 9000
